apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kafka

resources:
  - kafka-configmap.yaml
  - order-service.yaml
  - payment-service.yaml
  - websocket-service.yaml
  - ingress.yaml
